### ISSUE TITLE
libGL error: MESA-LOADER: failed to open iris / swrast

### ISSUE THREAD

**Issue by jagiella** [Open-Wine-Components/ULWGL#211] opened 2024-10-09 14:48 UTC
Installed debian packages on ubuntu 24.04 and trying to run a game:

```bash
$ WINEPREFIX=~/Games/game/ GAMEID=0 umu-run ~/path/to/game.exe 
UMU-Proton is up to date
steamrt is up to date
pressure-vessel-wrap[81051]: W: Using glibc from provider system for some but not all architectures! Arbitrarily using provider locales.
pressure-vessel-wrap[81051]: W: Using libdrm from provider system for some but not all architectures! Will take /usr/share/libdrm from provider.
pressure-vessel-wrap[81051]: W: Using libGLX_mesa.so.0 from provider system for some but not all architectures! Will take /usr/share/drirc.d from provider.
setlocale "en_US.UTF-8": No such file or directory
pressure-vessel-locale-gen: Missing locale en_US.UTF-8
pressure-vessel-locale-gen: Generating locale de_DE.UTF-8...
pressure-vessel-locale-gen: Generated locale de_DE.UTF-8 successfully
pressure-vessel-locale-gen: Generating locale en_US.UTF-8...
pressure-vessel-locale-gen: Generated locale en_US.UTF-8 successfully
pressure-vessel-adverb[81102]: W: Container startup will be faster if missing locales are created at OS level
ProtonFixes[81148] INFO: Running protonfixes
ProtonFixes[81148] INFO: Running checks
ProtonFixes[81148] INFO: All checks successful
ProtonFixes[81148] INFO: Using global defaults for UNKNOWN (0)
ProtonFixes[81148] INFO: No global protonfix found for UNKNOWN (0)
Proton: /home/user/path/to/game.exe
Proton: Executable a unix path, launching with /unix option.
wine: using kernel write watches, use_kernel_writewatch 1.
fsync: up and running.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: Read access denied for device L"\\??\\D:\\", FS volume label and serial are not available.
libGL error: MESA-LOADER: failed to open iris: /usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/dri)
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  392
  Current serial number in output stream:  391
```

```bash
$ locate iris_dri.so
/usr/lib/x86_64-linux-gnu/dri/iris_dri.so
$ locate swrast.so
/usr/lib/x86_64-linux-gnu/dri/kms_swrast_dri.so
/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
```

**Comment by GloriousEggroll** [comment] 2024-10-09 16:21
you are missing 32 bit packages:
/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/dri/iris_dri.so
/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/dri/swrast_dri.so

i386 is 32 bit. you only have 64 bit installed (x86_64):

$ locate iris_dri.so
/usr/lib/x86_64-linux-gnu/dri/iris_dri.so
$ locate iris_dri.so
/usr/lib/x86_64-linux-gnu/dri/kms_swrast_dri.so
/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so

**Comment by GloriousEggroll** [comment] 2024-10-12 12:12
closing this, as noted it's an issue with missing packages on your system, not an issue on the umu side. you need 32 bit packages for mesa dri.

**Comment by jagiella** [comment] 2024-10-13 10:31
Well I installed the 32-bit versions via:
```bash
$ sudo dpkg --add-architecture i386 && sudo apt update
$ sudo apt install libgl1-mesa-dri:i386
```

Now I should have all dependencies, right?
```
$ locate iris_dri.so swrast_dri.so
/usr/lib/i386-linux-gnu/dri/iris_dri.so
/usr/lib/i386-linux-gnu/dri/kms_swrast_dri.so
/usr/lib/i386-linux-gnu/dri/swrast_dri.so
/usr/lib/x86_64-linux-gnu/dri/iris_dri.so
/usr/lib/x86_64-linux-gnu/dri/kms_swrast_dri.so
/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
```

But still getting the same error:
```bash
libGL error: MESA-LOADER: failed to open iris: /usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/dri)
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  390
  Current serial number in output stream:  389
```

**Comment by GloriousEggroll** [comment] 2024-10-13 15:01
I've managed to reproduce this in a vm, looking into it

**Comment by GloriousEggroll** [comment] 2024-10-13 15:37
it seems on ubuntu pressure-vessel is not generating the 32 bit dri opengl overrides. 64 bit is generated fine and should work -- can you try a 64 bit game just to be sure?

Here is what I found so far:

ubuntu overrides for 32 bit missing dri folder + shortcuts and a few other folders:
![bubuntu](https://github.com/user-attachments/assets/ba654cf8-8dde-4bd4-b604-26b5f15ac07d)

nobara for comparison:
![noburduh](https://github.com/user-attachments/assets/74c47ae9-e7f3-4c84-b99f-f248b2993865)

that missing dri folder is what contains the opengl overrides for allowing 32 bit opengl games and applications to run

**Comment by R1kaB3rN** [comment] 2024-10-13 18:49
This bug is confirmed on Ubuntu, and a proper solution is being investigated. For now, as a workaround, please set:

LD_LIBRARY_PATH=/usr/lib/i386-linux-gnu/dri:${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}

or

LIBGL_DRIVERS_PATH=/usr/lib/i386-linux-gnu/dri:/usr/lib/x86_64-linux-gnu/dri:${LIBGL_DRIVERS_PATH:+:$LIBGL_DRIVERS_PATH}

**Comment by jagiella** [comment] 2024-10-13 20:22
I had one more package to install in order to make the game run:
```bash
sudo apt install libglx-mesa0:i386
```

This warning made me aware:
```
pressure-vessel-wrap[24887]: W: Using libGLX_mesa.so.0 from provider system for some but not all architectures! Will take /usr/share/drirc.d from provider.
```

But the game (starcraft 1) runs kind of slow as it does not seem to be using the nvidia graphics card at all, but the intel graphics instead.

**Comment by R1kaB3rN** [comment] 2024-10-13 20:29
Thanks for confirming. If you needed to install another package then we’ll need to update the dependencies for the .deb package.

Also, do you mind pasting the exact command you used to launch your game?

**Comment by R1kaB3rN** [comment] 2024-10-13 20:37
> But the game (starcraft 1) runs kind of slow as it does not seem to be using the nvidia graphics card at all, but the intel graphics instead.

Not being able to run your game due to missing graphics drivers in the container and experiencing a performance degradation are two separate things/issues.

**Comment by jagiella** [comment] 2024-10-13 20:58
I purged both libraries:
```bash
sudo apt purge libgl1-mesa-dri:i386 libglx-mesa0:i386
sudo apt autopurge
```

On a clean WINEPREFIX the game installs (note: the installer has a GUI, but obviously doesn't use openGL) without problems.

But running the game fails with the berfore mentioned errors/warnings:
```bash
$ WINEPREFIX=~/Games/starcraft/ GAMEID=0 umu-run ~/Games/starcraft/drive_c/Programme/Starcraft/StarCraft.exe 
UMU-Proton is up to date
steamrt is up to date
pressure-vessel-wrap[30822]: W: Using glibc from provider system for some but not all architectures! Arbitrarily using provider locales.
pressure-vessel-wrap[30822]: W: Using libdrm from provider system for some but not all architectures! Will take /usr/share/libdrm from provider.
pressure-vessel-wrap[30822]: W: Using libGLX_mesa.so.0 from provider system for some but not all architectures! Will take /usr/share/drirc.d from provider.
setlocale "en_US.UTF-8": No such file or directory
pressure-vessel-locale-gen: Missing locale en_US.UTF-8
pressure-vessel-locale-gen: Generating locale de_DE.UTF-8...
pressure-vessel-locale-gen: Generated locale de_DE.UTF-8 successfully
pressure-vessel-locale-gen: Generating locale en_US.UTF-8...
pressure-vessel-locale-gen: Generated locale en_US.UTF-8 successfully
pressure-vessel-adverb[30871]: W: Container startup will be faster if missing locales are created at OS level
ProtonFixes[30920] INFO: Running protonfixes
ProtonFixes[30920] INFO: Running checks
ProtonFixes[30920] INFO: All checks successful
ProtonFixes[30920] INFO: Using global defaults for UNKNOWN (0)
ProtonFixes[30920] INFO: No global protonfix found for UNKNOWN (0)
Proton: /home/user/Games/starcraft/drive_c/Programme/Starcraft/StarCraft.exe
Proton: Executable a unix path, launching with /unix option.
wine: using kernel write watches, use_kernel_writewatch 1.
fsync: up and running.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
libGL error: MESA-LOADER: failed to open iris: /usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/dri)
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  392
  Current serial number in output stream:  391
```

Then I install both 32bit mesa packages:
```bash
sudo apt install libgl1-mesa-dri:i386 libglx-mesa0:i386
```

And the game runs (slowly):
```bash
$ WINEPREFIX=~/Games/starcraft/ GAMEID=0 umu-run ~/Games/starcraft/drive_c/Programme/Starcraft/StarCraft.exe 
UMU-Proton is up to date
steamrt is up to date
setlocale "en_US.UTF-8": No such file or directory
pressure-vessel-locale-gen: Missing locale en_US.UTF-8
pressure-vessel-locale-gen: Generating locale de_DE.UTF-8...
pressure-vessel-locale-gen: Generated locale de_DE.UTF-8 successfully
pressure-vessel-locale-gen: Generating locale en_US.UTF-8...
pressure-vessel-locale-gen: Generated locale en_US.UTF-8 successfully
pressure-vessel-adverb[31743]: W: Container startup will be faster if missing locales are created at OS level
ProtonFixes[31789] INFO: Running protonfixes
ProtonFixes[31789] INFO: Running checks
ProtonFixes[31789] INFO: All checks successful
ProtonFixes[31789] INFO: Using global defaults for UNKNOWN (0)
ProtonFixes[31789] INFO: No global protonfix found for UNKNOWN (0)
Proton: /home/user/Games/starcraft/drive_c/Programme/Starcraft/StarCraft.exe
Proton: Executable a unix path, launching with /unix option.
wine: using kernel write watches, use_kernel_writewatch 1.
fsync: up and running.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
```
Note: Setting LD_LIBRARY_PATH or LIBGL_DRIVERS_PATH was not necessary.

**Comment by GloriousEggroll** [comment] 2024-10-13 22:46
> I had one more package to install in order to make the game run:
> 
> ```shell
> sudo apt install libglx-mesa0:i386
> ```
> 
> This warning made me aware:
> 
> ```
> pressure-vessel-wrap[24887]: W: Using libGLX_mesa.so.0 from provider system for some but not all architectures! Will take /usr/share/drirc.d from provider.
> ```
> 
> But the game (starcraft 1) runs kind of slow as it does not seem to be using the nvidia graphics card at all, but the intel graphics instead.

if it's trying to use opengl for the game and you're on a laptop you probably also need to make sure you have 32 bit nvidiia drivers installed and use the nvidia environment variables for opengl offloading

**Comment by GloriousEggroll** [comment] 2024-10-13 22:56
the good news is this isn't a bug with umu or its dependencies but rather a quirk caused by Ubuntu not shipping 32 bit mesa libraries OOTB -- which coincidentally causes 32 bit games to not be able to run

**Closed as completed** 2024-10-14 16:13 UTC

**Comment by Tuupertunut** [comment] 2026-01-19 16:53
I hit this problem when installing umu through uv on Ubuntu. The uv installation instructions have nothing to indicate that you might need to install additional libraries for Ubuntu. It might be worth it to add a special Ubuntu section to the readme to inform about issues with Ubuntu installations.
