### ISSUE TITLE
GAMEID seems to be mandatory now

### ISSUE THREAD

**Issue by Ketrel** [Open-Wine-Components/ULWGL#100] opened 2024-05-04 16:41 UTC
I just updated to the latest git, and now when I run with `GAMEID=` I get

```
Updating launcher to 0.1-RC4-47-g24e3f09
Updating runner to 0.1-RC4-47-g24e3f09
ERROR:  BaseException
Traceback (most recent call last):
  File "/home/master/.local/share/umu-launcher/umu_run.py", line 408, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/master/.local/share/umu-launcher/umu_run.py", line 381, in main
    check_env(env)
  File "/home/master/.local/share/umu-launcher/umu_run.py", line 127, in check_env
    raise ValueError(err)
ValueError: Environment variable not set or is empty: GAMEID
WARNING:  Runtime Platform not found
```

Problem is it's not a game/program with an ID

**Comment by R1kaB3rN** [comment] 2024-05-04 17:17
Thanks for reporting this. 

Yes, this is by design because the `GAMEID` must be set and assigned a value. It **cannot** be empty, and I'm sorry if this was not clearer because the man pages does give that impression in its examples so I will update them shortly.

**Comment by R1kaB3rN** [comment] 2024-05-04 17:25
Whoops. Actually, the examples there all list a GAMEID with a value. Aside from that, I think the PROTONPATH and WINEPREFIX environment variables should definitely be assigned a value there, otherwise an error will be raised.

Still, the GAMEID environment variable with a value is still strictly required. Just be sure that no fix already exists for that ID, such as GAMEID=0

**Comment by R1kaB3rN** [comment] 2024-05-04 17:50
Closing because this is not a current bug and this was a bug in the launcher that was fixed in https://github.com/Open-Wine-Components/umu-launcher/commit/e8acb0ac7cb9c17ff833dcf68deedab705803793

**Closed as completed by R1kaB3rN** 2024-05-04 17:50 UTC
