### ISSUE TITLE
Wine Mono not installed

### ISSUE THREAD

**Issue by wannkunstbeikor** [Open-Wine-Components/ULWGL#89] opened 2024-04-14 09:18 UTC
When I use umu-run to launch a .NET Framework 4.8 application with UMU-Proton, so just not setting the PROTONPATH env it will not work and wine will log the error `00e4:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed`.
If I set the PROTONPATH to my installed GE-Proton9-2 it works fine. No idea if this is an issue on my end, but since GE-Proton seems to work I think it might be an issue with UMU-Proton.
Im using the latest umu-launcher [commit](https://github.com/Open-Wine-Components/umu-launcher/commit/67182baca2f8df55736fc388a040bd5ae11f04df) at the moment of writing this.

**Comment by R1kaB3rN** [comment] 2024-04-14 22:31
> When I use umu-run to launch a .NET Framework 4.8 application with UMU-Proton, so just not setting the PROTONPATH env it will not work and wine will log the error `00e4:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed`. If I set the PROTONPATH to my installed GE-Proton9-2 it works fine. No idea if this is an issue on my end, but since GE-Proton seems to work I think it might be an issue with UMU-Proton. Im using the latest umu-launcher [commit](https://github.com/Open-Wine-Components/umu-launcher/commit/67182baca2f8df55736fc388a040bd5ae11f04df) at the moment of writing this.

Thanks for reporting this issue. Did you happen to already confirm that this issue also exists in upstream Proton -- Proton 9 (Beta 16)? If it doesn't work in upstream Proton but in GE, then there must be a patch somewhere in GE's build that fixes your problem and that this not a problem with the launcher but a possible regression upstream. If that's the case, you can configure umu to use GE-Proton by passing` PROTONPATH=GE-Proton` for that game.

**Comment by wannkunstbeikor** [comment] 2024-04-15 14:35
It works fine with Proton 9 beta 16 (i just downloaded the 9 beta from steam)

**Comment by R1kaB3rN** [comment] 2024-04-16 22:22
> It works fine with Proton 9 beta 16 (i just downloaded the 9 beta from steam)

That's strange, because Wine Mono is included in UMU-Proton. To confirm, you still experience this problem in a new Wine prefix? If the previous prefix was created from a different Proton or Wine build, then things are likely to break. For instance, transitioning from UMU-Proton -> GE-Proton, I've observed that I am always displayed a prompt about how Wine could not find Wine Mono, and my protonfixes applied to that prefix would be reset/overwritten

**Comment by GloriousEggroll** [comment] 2024-04-18 00:40
If you change versions and use the same prefix you -will- as R1ka said hit wine mono install request because different proton versions use different versions of mono. Please double check this on a clean prefix using UMU-Proton

**Comment by wannkunstbeikor** [comment] 2024-04-18 11:41
> To confirm, you still experience this problem in a new Wine prefix?

yes i made it generate a new folder for the prefix

**Comment by wannkunstbeikor** [comment] 2024-04-18 11:46
`rm -r /home/jona/wine`
`WINEPREFIX=/home/jona/wine GAMEID=0 WINEDEBUG=error-all umu-run /home/jona/Downloads/FrostyEditor/FrostyEditor.exe`
```
UMU-Proton is up to date
x86_64-linux-gnu-capsule-capture-libs: warning: Dependencies of libnvidia-pkcs11.so.550.67 not found, ignoring: Missing dependencies: Could not find "libcrypto.so.1.1" in LD_LIBRARY_PATH "", ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
Proton: Upgrading prefix from None to UMU-Proton-9.0-200-2 (/home/jona/wine/)
ProtonFixes[43708] INFO: Running protonfixes
ProtonFixes[43708] INFO: Running checks
ProtonFixes[43708] INFO: All checks successful
ProtonFixes[43708] INFO: Using global defaults for UNKNOWN (0)
ProtonFixes[43708] INFO: No global protonfix found for UNKNOWN (0)
Proton: /home/jona/Downloads/FrostyEditor/FrostyEditor.exe
Proton: Executable a unix path, launching with /unix option.
esync: up and running.
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00e0:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed
```
this is what i did and the output

**Comment by wannkunstbeikor** [comment] 2024-04-24 09:57
okay i think i know what the issue is, the default prefix of UMU-Proton is missing some stuff, which the ge one has.
```
Only in GE-Proton9-2/files/share/default_pfx/drive_c/windows: Installer
Only in GE-Proton9-2/files/share/default_pfx/drive_c/windows: Microsoft.NET
```
if i generate it manually with wineboot from umu-proton it will also work fine, but not when umu-proton uses the default prefix to generate it

**Comment by loathingKernel** [comment] 2024-04-24 11:13
The issue is with UMU-Proton, and the version of `wine-mono` it bundles when building it.

The wine version built with UMU-Proton uses `wine-mono 8.1.0` https://github.com/ValveSoftware/wine/blob/a0ede0fe99299a09d97a11cd62c67a7cd53ae09f/dlls/mscoree/mscoree_private.h#L48
but due to an oversight in the UMU-Proton makefile version `9.0.0` is bundled with it, https://github.com/Open-Wine-Components/umu-proton/blob/proton_9.0/Makefile.in#L961

**Comment by wannkunstbeikor** [comment] 2024-04-24 11:16
I mean GE-Proton uses wine-mono 9.0.0 and that what i compared it to and it worked

**Comment by wannkunstbeikor** [comment] 2024-04-24 17:39
So if I understand it correctly, the wine submodule needs to be updated and then it should work fine?

**Comment by R1kaB3rN** [comment] 2024-07-01 17:47
Closing as [this problem should be addressed in the latest UMU-Proton](https://github.com/Open-Wine-Components/umu-proton/releases/tag/UMU-Proton-9.0-2)

**Closed as completed by R1kaB3rN** 2024-07-01 17:47 UTC
Labels: bug
