### ISSUE TITLE
Pressure vessel not present in .local/share/umu/ - Lutris

### ISSUE THREAD

**Issue by sergen213** [Open-Wine-Components/ULWGL#226] opened 2024-10-12 14:30 UTC
After the major update umu didn't download/copy pressure-vessel to runtime folder and now it fails to run games with proton

![log](https://github.com/user-attachments/assets/e6a008cb-f61b-472f-8ae9-810d15eac771)

After copying pressure-vessel from steamapps, I was able to run the games with proton.

**Comment by R1kaB3rN** [comment] 2024-10-12 15:12
The runtime update bug is fixed in https://github.com/Open-Wine-Components/umu-launcher/releases/tag/1.1.2, so you will never have to manually download or copy the pressure-vessel directory again. 

Now, Lutris will be responsible for updating their runtime so users can get the fix for future runtime updates.

**Comment by R1kaB3rN** [comment] 2024-10-12 15:17
Closing, since I’m confident this is not a bug with the current launcher and our test in the CI strongly proves that there was no problem when updating the runtime from an old to the latest sniper build version.

**Closed as completed by R1kaB3rN** 2024-10-12 15:17 UTC
