### ISSUE TITLE
GE-Proton9-5?

### ISSUE THREAD

**Issue by Pednick** [Open-Wine-Components/ULWGL#102] opened 2024-05-14 15:07 UTC
Yeah for me GAMEID=umu-CheatEngine PROTONPATH=GE-Proton9-4 umu-run winecfg
runs fine but GAMEID=umu-CheatEngine PROTONPATH=GE-Proton9-5 umu-run winecfg
does and spits out this error:
Traceback (most recent call last):
  File "/usr/share/umu/umu_run.py", line 408, in <module>
    sys.exit(main())
  File "/usr/share/umu/umu_run.py", line 400, in main
    build_command(env, UMU_LOCAL, root, command, opts)
  File "/usr/share/umu/umu_run.py", line 257, in build_command
    raise FileNotFoundError(err)
    
 I installed as per instructions:
 
 git clone https://github.com/Open-Wine-Components/umu-launcher.git

cd umu-launcher

This I had to find out on my own to run:

git submodule update --init

./configure.sh --prefix=/usr

make

sudo make install

So I'm guessing the launcher needs to be upgraded for GE-Proton9-5.

**Comment by R1kaB3rN** [comment] 2024-05-14 16:36
The command `GAMEID=umu-CheatEngine PROTONPATH=GE-Proton9-5 umu-run winecfg` fails because you do not have GE-Proton9-5 installed in your system. The launcher is trying to find GE-Proton9-5 in `~/.local/share/Steam/compatibilitytools.d` but it's not there. You can easily download it by running the same command but by setting `PROTONPATH=GE-Proton` instead or, if it's already installed somewhere, by specifying the path to `PROTONPATH` (e.g., `PROTONPATH=/usr/share/steam/compatibilitytools.d/GE-Proton9-5`). Afterwards, you can rerun the command, but with `PROTONPATH=GE-Proton9-5` set which will work.

Also, if you're able to, please install the launcher using your distribution's package manager. Installing via make is bad practice, and this will be considered for removal in the next release.

**Comment by R1kaB3rN** [comment] 2024-05-14 16:39
Closing because this is currently not a bug with the launcher. If you disagree, please feel free to reopen but listing the complete traceback, precise steps to reproduce, and the version (commit) of the launcher.

**Closed as completed by R1kaB3rN** 2024-05-14 16:39 UTC

**Comment by Pednick** [comment] 2024-05-14 16:48
> The command `GAMEID=umu-CheatEngine PROTONPATH=GE-Proton9-5 umu-run winecfg` fails because you do not have GE-Proton9-5 installed in your system. The launcher is trying to find GE-Proton9-5 in `~/.local/share/Steam/compatibilitytools.d` but it's not there. You can easily download it by running the same command but by setting `PROTONPATH=GE-Proton` instead or, if it's already installed somewhere, by specifying the path to `PROTONPATH` (e.g., `PROTONPATH=/usr/share/steam/compatibilitytools.d/GE-Proton9-5`). Afterwards, you can rerun the command, but with `PROTONPATH=GE-Proton9-5` set which will work.
> 
> Also, if you're able to, please install the launcher using your distribution's package manager. Installing via make is bad practice, and this will be considered for removal in the next release.

Oh ok thank you, I actally prefer your source based install since I'm on Ubuntu.
