### ISSUE TITLE
Continuity of my last issue

### ISSUE THREAD

**Issue by mistermookiefun** [Open-Wine-Components/ULWGL#87] opened 2024-04-07 23:03 UTC
I applied what you said:
You were getting this error because the git submodules were not initialized which can be done via: git submodule update --init --filter=tree:0 --recursive

On an updated git version with submodules initialized then I make installed it.
Here is the error I get:
Exception in thread Thread-1 (setup_umu):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/umu/umu_util.py", line 145, in setup_umu
    return _update_umu(root, local, STEAM_COMPAT, json, _get_json(local, CONFIG))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/umu/umu_util.py", line 384, in _get_json
    json = load(file)
           ^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mistermookiefun** [comment] 2024-04-07 23:04
But the exes launch though

**Comment by R1kaB3rN** [comment] 2024-04-08 03:58
This issue lies within your `umu_versions.json` file which is corrupted for some reason, and I can reproduce that error by clearing the contents of `umu_versions.json` in my local directory. If you either nuke your `~/.local/share/umu` directory or copy the configuration file from `/usr/share/umu`, assuming that also isn't corrupted as well, you should not be experiencing this problem anymore. Please confirm this with me. Still, I'm curious how that happened...

Aside from that error, I suggest you do not install directly via make and instead use your distribution's package manager. This is poor practice and in the future, this will be considered for removal.

**Comment by mistermookiefun** [comment] 2024-04-08 18:44
That's curious, I didn't nuke anything, here's the content
Content:
```
{
  "umu": {
    "versions": {
      "launcher": "0.1-RC3-373-g2d44ca8",
      "runner": "0.1-RC3-373-g2d44ca8",
      "runtime_platform": "sniper_platform_0.20240125.75305",
      "reaper": "0.1-RC3-373-g2d44ca8",
      "pressure_vessel": "v0.20240212.0"
    }
  }
}
```
Yeah I know about the make but the AUR maintainer isn't up-to-date with the version. the checksums are not valid and it doesn't install properly, at least on my system.
By the way, BIIIIIIIIIIIIG THANK YOU for this project, you made a person happy <3

**Comment by loathingKernel** [comment] 2024-04-08 19:00
> Yeah I know about the make but the AUR maintainer isn't up-to-date 

The AUR package has been updated https://aur.archlinux.org/cgit/aur.git/commit/?h=umu-launcher&id=bcd2fccef91d7bd9f91b75d0075de8c02fdbaa43 since your previous issue.

> the checksums are not valid and it doesn't install properly, at least on my system.

The checksums are valid but in case you are using Manjaro, you might not have pacman 6.1 yet, you can see the build completes fine here https://github.com/loathingKernel/PKGBUILDs/actions/runs/8582810729

**Comment by R1kaB3rN** [comment] 2024-04-08 19:29
> By the way, BIIIIIIIIIIIIG THANK YOU for this project, you made a person happy <3

You're welcome and I'm glad to hear that :smile:



> That's curious, I didn't nuke anything, here's the content Content:
> 
> ```
> {
>   "umu": {
>     "versions": {
>       "launcher": "0.1-RC3-373-g2d44ca8",
>       "runner": "0.1-RC3-373-g2d44ca8",
>       "runtime_platform": "sniper_platform_0.20240125.75305",
>       "reaper": "0.1-RC3-373-g2d44ca8",
>       "pressure_vessel": "v0.20240212.0"
>     }
>   }
> }
> ```
> 

Just to confirm, you still get this error after clearing your `~/.local/share/umu` directory? Because I cannot reproduce this error any other way besides clearing the contents of the config file.

**Comment by mistermookiefun** [comment] 2024-04-08 20:33
I installed it with manual make install and got that error out of the box

**Comment by mistermookiefun** [comment] 2024-04-08 20:33
OK will try to install it with the AUR later today then

**Comment by R1kaB3rN** [comment] 2024-04-09 16:32
> OK will try to install it with the AUR later today then

In the meantime, I will close this because I am not convinced this is a current bug.

Feel free to reopen, but please be sure to clear your `~/.local/share/umu` directory, cite the install source along with each step, and report back after running the launcher with `UMU_LOG=debug`

**Closed as completed by R1kaB3rN** 2024-04-09 16:32 UTC
Labels: can't reproduce
