### ISSUE TITLE
Trainer won't start when game is started

### ISSUE THREAD

**Issue by Pednick** [Open-Wine-Components/ULWGL#120] opened 2024-06-20 12:51 UTC
When I run GAMEID=umu-TombRaider PROTONPATH=GE-Proton umu-run $HOME/Games/umu/umu-TombRaider/drive_c/'R.G. Catalyst'/'Tomb Raider'/TombRaider.exe

And then run GAMEID=umu-TombRaider PROTONPATH=GE-Proton umu-run $HOME/Games/umu/umu-TombRaider/drive_c/'R.G. Catalyst'/'Tomb Raider'/'Tomb Raider Game of The Year Edition V Plus 5 Trainer.EXE'

My game starts up but the trainer doesn't, but when I quit the game, the trainer starts up. And yes the trainer is the right version of the game. How would I go about setting this up properly so both start up?

**Comment by imLinguin** [comment] 2024-06-20 16:15
Try running the second executable with `PROTON_VERB=run` env var

**Comment by Pednick** [comment] 2024-06-20 16:34
> Try running the second executable with `PROTON_VERB=run` env var

How would I run that?  Can you give an example from my post?

**Comment by R1kaB3rN** [comment] 2024-06-20 21:47
> How would I run that? Can you give an example from my post?

Using your above command, it would be:
> PROTON_VERB=runinprefix GAMEID=umu-TombRaider PROTONPATH=GE-Proton umu-run $HOME/Games/umu/umu-TombRaider/drive_c/'R.G. Catalyst'/'Tomb Raider'/'Tomb Raider Game of The Year Edition V Plus 5 Trainer.EXE'

**Comment by Pednick** [comment] 2024-06-20 21:49
> > How would I run that? Can you give an example from my post?
> 
> Using your above command, it would be:
> 
> > PROTON_VERB=runinprefix GAMEID=umu-TombRaider PROTONPATH=GE-Proton umu-run $HOME/Games/umu/umu-TombRaider/drive_c/'R.G. Catalyst'/'Tomb Raider'/'Tomb Raider Game of The Year Edition V Plus 5 Trainer.EXE'

Ok thanks, I'll give it a try.

**Comment by R1kaB3rN** [comment] 2024-06-20 21:52
Closing as its a duplicate of https://github.com/Open-Wine-Components/umu-launcher/issues/85 and a section has been added to the [project's wiki for this issue](https://github.com/Open-Wine-Components/umu-launcher/wiki/Frequently-asked-questions-(FAQ)).

**Closed as completed by R1kaB3rN** 2024-06-20 21:52 UTC

**Comment by Pednick** [comment] 2024-06-20 21:54
> Closing as its a duplicate of #85 and a section has been added to the [project's wiki for this issue](https://github.com/Open-Wine-Components/umu-launcher/wiki/Frequently-asked-questions-(FAQ)).

Thank you very much, that did the trick.
