### ISSUE TITLE
Can't use Proton GE installed through AUR

### ISSUE THREAD

**Issue by Yuri-K7** [Open-Wine-Components/ULWGL#88] opened 2024-04-13 16:41 UTC
I tried with Lutris 5.17 to use the proton-ge-custom-bin package from AUR, and I can't use it if I don't make my own symbolic link :

```
ln -s /usr/share/steam/compatibilitytools.d/proton-ge-custom "/home/yuri/.steam/root/steamapps/common/Proton GE"
```

The "GE-Proton (Latest)" from the wine runner selection installs UMU-Proton which doesn't have the gstreamer fixes I want.

Using PROTONPATH=GE-Proton seems to download it again even though it's already installed.

**Comment by Aqa-Ib** [comment] 2024-04-13 23:12
Have you tried with `PROTONPATH=/usr/share/steam/compatibilitytools.d/proton-ge-custom` ?

**Comment by R1kaB3rN** [comment] 2024-04-14 01:42
umu _can_ support checking at `/usr/share/steam/compatibilitytools.d` for GE-Proton. However, that path isn't official as it's a system path invented by some AUR maintainer so that they can distribute proton-ge to users. Since umu automatically downloads and uses the latest GE-Proton in behalf of the user, I'd recommend you'd not use unofficial packages because umu comes with the following advantages:

- Not being dependent of the AUR maintainer for updates
- Having less dependencies installed
- Not requiring root privileges for its installation
- Being directly supported by upstream -- Open Wine Components members

Due to these reasons, I'm not really in favor of supporting this feature

**Comment by loathingKernel** [comment] 2024-04-14 04:25
> However, that path isn't official as it's a system path invented by some AUR maintainer so that they can distribute proton-ge to users.

The system-wide path is an officially supported feature of Steam since 2019 https://github.com/ValveSoftware/steam-for-linux/issues/6310 .

The list of distribution that use the system-wide path to ship Proton packages is small enough though to not warrant supporting it https://repology.org/project/proton-ge-custom/versions

**Comment by R1kaB3rN** [comment] 2024-04-14 05:55
Closing unless there's a more compelling reason to support this feature. I believe it's more advantageous and simpler if umu downloads GE-Proton for you. It would also require less resources since compressing the package via pacman results in high CPU utilization and can take quite a bit of time.

Like Aqa-Ib suggested, you can add that environment variable in Lutris if you still insist to use the one provided by the AUR package.

**Closed as completed by R1kaB3rN** 2024-04-14 05:55 UTC

**Comment by Yuri-K7** [comment] 2024-04-14 11:06
Using the suggested environment variable it does indeed work with "GE-Proton (Latest)" but it's still not listed besides that, is it a lutris thing as umu only manages "GE-Proton (Latest)" ?

I agree that this AUR package could be considerate obsolete after the recent changes, but I still don't feel totally compelled.

But I guess my issues are more of a Lutris integration issue, PROTONPATH env var as a Lutris option, showing a progress bar while downloading, be able to skip the download with a button... which is still experimental for now.

If I want to update without launching a game through Lutris, there's no umu command dedicated to that right ? or do you intend that steam users would also use "GE-Proton (Latest)" (I only see umu-launcher and already installed Protons) ? The advantage of the AUR package was that steam games set with "Proton GE" would use the current installed version without having to specifying the version.

Can the download be skipped or disabled ?

**Comment by R1kaB3rN** [comment] 2024-04-14 22:00
> Using the suggested environment variable it does indeed work with "GE-Proton (Latest)" but it's still not listed besides that, is it a lutris thing as umu only manages "GE-Proton (Latest)" ?

Hmm, I can confirm this. After installing the proton-ge-custom-bin package, I can observe that the build will not be listed in the dropdown menu. Later I can try to make a patch for this problem in Lutris, but it'll be up to upstream to accept it.

> But I guess my issues are more of a Lutris integration issue, PROTONPATH env var as a Lutris option, showing a progress bar while downloading, be able to skip the download with a button... which is still experimental for now.

I agree with you here on the features you listed, and in a future release you can expect Lutris to implement some of them. In particular, expect at least to have a download progress bar and the option to cancel the download. For now, it just delegates the downloading of builds to umu.

> Can the download be skipped or disabled ?

To skip the download, pass a path to a Proton build to `PROTONPATH`. In your case, it's the path to the AUR build. Doing this will also result in faster start up times for launching games because no outgoing requests will be made.
