### ISSUE TITLE
umu flatpak installation error

### ISSUE THREAD

**Issue by rairay91** [Open-Wine-Components/ULWGL#162] opened 2024-07-31 16:26 UTC
What's wrong here?
![1722442803696](https://github.com/user-attachments/assets/2607a211-fd50-45d1-b420-630f107b0188)

**Comment by R1kaB3rN** [comment] 2024-07-31 22:29
Because the remote repository `umu-repo` already exists as indicated by `error: Remote umu-repo already exists`. See `$HOME/.local/share/flatpak/repo/config ` in your system for the entry. For more help, consult the Flatpak man pages or other resources online for more details on those specific commands or error messages experienced by other users.

Putting this problem aside though, you do not want to be using the Flatpak release tarball at this point as its way out of date. For now, if you insist on using the Flatpak, please build it locally until umu-launcher is officially on Flathub.

**Comment by rairay91** [comment] 2024-08-01 10:19
Also, i dont know how to use umu that got installed with lutris from flatpak?

**Comment by rairay91** [comment] 2024-08-01 17:55
> Because the remote repository `umu-repo` already exists as indicated by `error: Remote umu-repo already exists`. See `$HOME/.local/share/flatpak/repo/config ` in your system for the entry. For more help, consult the Flatpak man pages or other resources online for more details on those specific commands or error messages experienced by other users.
> 
> Putting this problem aside though, you do not want to be using the Flatpak release tarball at this point as its way out of date. For now, if you insist on using the Flatpak, please build it locally until umu-launcher is officially on Flathub.

OK, i was able to install umu from flatpak (as system using this command flatpak --system install umu-repo org.openwinecomponents.umu.umu-launcher).

But i have another problem. This error shown while setting prefix ->

flatpak run --env=GAMEID=umu-spaceengine --env=WINEPREFIX=/home/hp/Games/Prefixes/umu-spaceengine org.openwinecomponents.umu.umu-launcher winecfg
WARNING:  Runtime Platform not found
Restoring Runtime Platform to sniper_platform_0.20240125.75305 ...
Downloading sniper_platform_0.20240125.75305, please wait ...
Downloading UMU-Proton-9.0-2.sha512sum ...
Downloading UMU-Proton-9.0-2.tar.gz ...
Exception in thread Thread-2 (setup_runtime):
Traceback (most recent call last):
File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
self.run()
File "/usr/lib/python3.11/threading.py", line 982, in run
self._target(*self._args, **self._kwargs)
File "/app/share/umu/umu_util.py", line 91, in setup_runtime
tar.extract(member, path=tmp)
File "/usr/lib/python3.11/tarfile.py", line 2298, in extract
self._extract_one(tarinfo, path, set_attrs, numeric_owner)
File "/usr/lib/python3.11/tarfile.py", line 2332, in _extract_one
self._handle_fatal_error(e)
File "/usr/lib/python3.11/tarfile.py", line 2328, in _extract_one
self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
File "/usr/lib/python3.11/tarfile.py", line 2411, in _extract_member
self.makefile(tarinfo, targetpath)
File "/usr/lib/python3.11/tarfile.py", line 2465, in makefile
copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
File "/usr/lib/python3.11/tarfile.py", line 255, in copyfileobj
dst.write(buf)
OSError: [Errno 28] No space left on device
ERROR:  BaseException
Traceback (most recent call last):
File "/app/share/umu/umu_run.py", line 385, in <module>
sys.exit(main())
^^^^^^
File "/app/share/umu/umu_run.py", line 359, in main
check_env(env)
File "/app/share/umu/umu_run.py", line 163, in check_env
get_umu_proton(env)
File "/app/share/umu/umu_dl_util.py", line 41, in get_umu_proton
if _get_latest(env, STEAM_COMPAT, tmp, files):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/share/umu/umu_dl_util.py", line 279, in _get_latest
_fetch_proton(env, tmp, files)
File "/app/share/umu/umu_dl_util.py", line 178, in _fetch_proton
file.write(resp.read())
OSError: [Errno 28] No space left on device

**Comment by R1kaB3rN** [comment] 2024-08-01 17:55
> Also, i dont know how to use umu that got installed with lutris from flatpak?

You currently can't use the system or Flatpak umu with the Lutris Flatpak, only the umu provided by Lutris. This is one of the disadvantages of using their Flatpak, and I believe this is something that would require changes to their manifest either by building it or having it as an extension once umu-launcher or a umu runtime is uploaded to Flathub.

If you want to use the latest umu that is installed on your system, you currently must use a system package along with those launchers.

**Comment by R1kaB3rN** [comment] 2024-08-01 17:57
> _fetch_proton(env, tmp, files) File "/app/share/umu/umu_dl_util.py", line 178, in _fetch_proton file.write(resp.read()) OSError: [Errno 28] No space left on device

Lutris is currently using the RC4 umu-launcher which is way out of date. I'm aware of that error and I believe the problem should have been addressed in the latest main branch. If you still experience that problem in main, please make a separate issue for it.

**Comment by rairay91** [comment] 2024-08-01 17:59
> > Also, i dont know how to use umu that got installed with lutris from flatpak?
> 
> You currently can't use the system or Flatpak umu with the Lutris Flatpak, only the umu provided by Lutris. This is one of the disadvantages of using their Flatpak, and I believe this is something that would require changes to their manifest either by building it or having it as an extension once umu-launcher or a umu runtime is uploaded to Flathub.
> 
> If you want to use the latest umu that is installed on your system, you currently must use a system package along with those launchers.

I m not using with lutris. I just installed umu from umu flatpak repo as mensioned on github page. I tried to run wineconfig command to set prefix for games(as mensioned on github). I got error mensioned above.

**Comment by rairay91** [comment] 2024-08-01 18:01
> > _fetch_proton(env, tmp, files) File "/app/share/umu/umu_dl_util.py", line 178, in _fetch_proton file.write(resp.read()) OSError: [Errno 28] No space left on device
> 
> Lutris is currently using the RC4 umu-launcher which is way out of date. I'm aware of that error and I believe the problem should have been addressed in the latest main branch. If you still experience that problem in main, please make a separate issue for it.

I was not using lutris. I was using native flatpak installed umu through terminal.

**Comment by R1kaB3rN** [comment] 2024-08-01 18:04
Closing because this is not a bug in the launcher and I believe I addressed the issue's original question.

> I was not using lutris. I was using native flatpak installed umu.

That umu is out of date. Please create a separate issue for the `OSError` if you can reproduce it in main by building it (e.g., `flatpak-builder --user --install --force-clean builddir org.openwinecomponents.umu.umu-launcher.yml`)

**Closed as completed by R1kaB3rN** 2024-08-01 18:04 UTC
Labels: question
