### ISSUE TITLE
[Best Practices] Should I Pull Request or just go with my fork?

### ISSUE THREAD

**Issue by tcsenpai** [Open-Wine-Components/ULWGL#42] opened 2024-02-25 21:33 UTC
Hi there!

Great work here, I absolutely love this idea and the realisation which is already quite stable :)

For my own benefit I replaced some components and tweaked the launcher to be more "integrated" (like "Open with...", a proper .desktop launcher, easier configuration, launchers support, [hopefully] streamlined execution...) as a fork (here https://github.com/tcsenpai/ULWGL-launcher-TCS), I was wondering if I should do a PR or go with my fork.

Sorry if the above sounds confusing, I'll explain.

My fork is basically a wrapper around ULWGL (not ulwgl-run) and is organised so that most of the actual codebase is moved into a "launcher" subfolder. Also I "removed" (well, gitignored) some components that I found not to be necessary due to the new Python implementation.

Aside from the fact that this is a completely different folder structure (making a merge look a bit arrogant from my side, as I am only doing a wrapper), just due to the fact that I have moved the codebase to a subfolder that would be a HUGE PR.

What's the consensus on what to do? I'd like to be helpful with my code, but I understand the points above and don't want to sound arrogant.

Though, of course my fork being a wrapper it would benefit from "automatic" version advancement in pair with this project.

Sorry for my English, I am not a native speaker.

**Comment by loathingKernel** [comment] 2024-02-25 22:13
Hello, and thank you for you interest in contributing! Indeed it was a good idea to create an issue, since these changes are quite disruptive. From a cursory look, I have to say that I like some of the ideas but my personal opinion is that as it is, the fork is incompatible with that ULWGL wants to be. The aim is to be a common backend to be used by other launchers, not to a fully fledged one itself. As such there are certain criteria that need to be met.

* ULWGL should not use anything but the Python standard library. This ensures compatibility without the need to install any dependencies.
* ULWGL should not output anything to `stdout`, as that space is reserved for the output of the command that is run inside the prefix. `print` should be directed to `stderr` at least.

I also see a few other code and functionality issues which could be considered regressions if this was to be merged as is, but I will not get into these as they are not relevant in the scope of this issue. In my personal opinion, if you would like to contribute some changes back, I would suggest to do so with targeted changes that do not disrupt the current structure. For example I am not against de-populating the main directory from the python files but the runtime files should not be moved imho.

If this aims to be a better TUI or CLI interface for ULWGL, which I can see the usefulness of, it would be better to be based on or using the existing python code and not re-write almost everything, as the existing code has gone through a few reviews already and also has extensive unittests, which is very important.

**Comment by tcsenpai** [comment] 2024-02-25 22:20
Thank you for your suggestions, which are exactly what I needed to improve my contribution!

The first point in particular tells me that my fork is indeed a fork and not a contribution to this particular project.

Also

> The goal is to be a common backend that can be used by other launchers.

Looks like UWine is "just" a PoC of that indeed! 

> If this aims to be a better TUI or CLI interface for ULWGL, which I can see the usefulness of, it would be better to be based on or using the existing python code and not re-write almost everything, as the existing code has gone through a few reviews already and also has extensive unittests, which is very important.

That's a very very helpful suggestion, thanks.

I'm going to rethink UWine deeply to understand which direction I want to go, feel free to close the topic if no further comment is needed and again compliments for the great work.

**Closed as completed** 2024-03-01 20:06 UTC
